### ISSUE TITLE
auto playlist navigation not working in armv7 and amd64

### ISSUE THREAD

**Issue by akararsse** [grafana/grafana-kiosk#32] opened 2020-04-16 09:38 UTC
I have tried release 1.0.1 and used the armv7 and amd64 binary packages in a Tinker board running in Tinker OS (debian) and Linux Mint respectively. The following Behaviour were observed: 
* Both the armv7 and amd64 binary files fills the fields in the login page of the grafana instance i am connecting to, thus auto login is working. 
* But after logging in it should redirect to the playlist, but instead it stays in the grafana main page . I have to manually click on the start playlist after navigating to the playlist page to start it. 
Here is the command that i am running and the outputs:

```bash
$ ./grafana-kiosk.linux.armv7 --URL https://insight.desec.io/grafana/playlists/play/1 --login-method local --username $uname --password $password --playlist
2020/04/16 11:15:18 playlist
2020/04/16 11:15:18 DISPLAY not set, autosetting to :0.0
2020/04/16 11:15:18 DISPLAY= :0.0
2020/04/16 11:15:18 XAUTHORITY not set, autosetting
2020/04/16 11:15:18 XAUTHORITY= /home/linaro/.Xauthority
2020/04/16 11:15:18 Launching local login kiosk
2020/04/16 11:15:20 KioskMode: Fullscreen
2020/04/16 11:15:20 Navigating to  https://insight.desec.io/grafana/playlists/play/1?inactive=1&kiosk=1&autofitpanels
```

**Comment by AlexHeylin** [comment] 2020-05-15 16:15
I'm new to this code, but from what I can make out - one the login is completed this code just lets Chrome get on with it - starting the playlist after login is down to Grafana telling Chrome what to do.  Have you confirmed that Chrome running on those same machines goes from the URL above to the playlist?
What version of Grafana? If not latest, please reproduce with latest stable.

**Comment by peterthomassen** [comment] 2020-05-15 17:00
Thanks for getting back, @AlexHeylin. Yes, the link works and does start the playlist if I manually login beforehand. The Grafana version we run is the current version from the official Docker image.

**Comment by AlexHeylin** [comment] 2020-05-16 02:33
@peterthomassen it might be the way you worded that or it might be what you're actually doing - so sorry to recheck this but it sounds like you're logging in and THEN calling the playlist url?

What happens if you log out of Grafana, close all browser windows, and then in a fresh Chrome window call the playlist url and login - does the playlist start?

I ask, because that's exactly what the code does (as far as I can tell).

**Comment by peterthomassen** [comment] 2020-05-16 11:29
Ah, you are right: If I use the link https://insight.desec.io/grafana/playlists/play/1?inactive=1&kiosk=1&autofitpanels without logging in first, I get direct to the log in page, and after log in, there's just the Grafana main page. The playlist does not start.

When opening the link while logged in, the playlist does start.

So it seems like the URL is correct, but the post-login redirect is not working properly. That's a Grafana bug, I suppose?

**Comment by peterthomassen** [comment] 2020-05-16 11:40
Actually, I double-checked versions, and apparently a new Grafana version has appeared since opening the bug. After the upgrade, the URL leads to the login form, and after login correctly redirects to the dashboard. So, I guess this has been fixed!

**Comment by AlexHeylin** [comment] 2020-05-16 14:47
Great news! Are you able to close this issue? If not, perhaps add "Resolved:" to the front of the title. As I'm not on the project team, I can't close it. Thanks

**Comment by briangann** [comment] 2020-05-16 17:59
there was a redirect bug in Grafana core causing this, took a while but the PR to fix it was merged in :)

**Closed by briangann** 2020-05-16 17:59 UTC
